# Generated by Django 5.2.6 on 2025-09-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='File',
        ),
    ]
