# Generated by Django 5.2.6 on 2025-09-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_externalurl_text_remove_file_title_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
